@startuml
class Kunde {
  + Kundennummer
  + Name
  + E-Mail
  + Adresse
  + Telefonnummer
  + Sperrstatus
  + Rabattstatus

}

class Barbetreiber {
  + Betreiber-ID
  + Name
  + E-Mail
  

}

class Cocktail {
  + Cocktail-ID
  + Name
  + Preis
  + Beschreibung
  + Kategorie
  }
  

class Zutat {
  + Zutaten-ID
  + Name
  + Kategorie
  + Preis pro Einheit
  
 
}

class Bestellung {
  + Bestellnummer
  + Bestelldatum
  + Lieferadresse
  + Gesamtpreis
  + Bestellstatus
 
}

class Bezahlung {
  + Zahlungs-ID
  + Zahlungsmethode
  + Zahlungsstatus
  }
  

class Werbung {
  + Betreff
  + Inhalt
  + Empfänger
  
}

Kunde "1" -- "N" Bestellung
Bestellung "N" -- "M" Cocktail
Cocktail "N" -- "M" Zutat
Bestellung "1" -- "1" Bezahlung
Werbung "N" -- "1" Kunde
Barbetreiber "1" -- "N" Cocktail : "verwaltet"
Barbetreiber "1" -- "N" Zutat : "aktualisiert"
Barbetreiber "1" -- "N" Werbung : "erstellt Kampagnen"
@enduml