@startuml
class Kunde {
  + Kundennummer
  + Name
  + E-Mail
  + Adresse
  + Telefonnummer
  + Sperrstatus
  + Rabattstatus
  --
  + Bestellung erstellen()
  + Bestellhistorie abrufen()
  + Rabatt anwenden()
}

class Barbetreiber {
  + Betreiber-ID
  + Name
  + E-Mail
  --
  + Cocktails verwalten()
  + Zutaten aktualisieren()
  + Marketing-Kampagnen erstellen()
}

class Cocktail {
  + Cocktail-ID
  + Name
  + Preis
  + Beschreibung
  + Kategorie
  --
  + Preis berechnen()
  + Details anzeigen()
}

class Zutat {
  + Zutaten-ID
  + Name
  + Kategorie
  + Preis pro Einheit
  --
  + Verfügbarkeit prüfen()
  + Preis zurückgeben()
}

class Bestellung {
  + Bestellnummer
  + Bestelldatum
  + Lieferadresse
  + Gesamtpreis
  + Bestellstatus
  --
  + Artikel hinzufügen()
  + Artikel entfernen()
  + Bestellung anzeigen()
  + Bestellung abschließen()
  + Bestellung stornieren()
}

class Bezahlung {
  + Zahlungs-ID
  + Zahlungsmethode
  + Zahlungsstatus
  --
  + Zahlung verarbeiten()
  + Zahlungsstatus prüfen()
}

class Marketing {
  + Betreff
  + Inhalt
  + Empfänger
  --
  + Email senden()
}

Kunde "1" -- "N" Bestellung
Bestellung "N" -- "M" Cocktail
Cocktail "N" -- "M" Zutat
Bestellung "1" -- "1" Bezahlung
Marketing "N" -- "1" Kunde
Barbetreiber "1" -- "N" Cocktail : "verwaltet"
Barbetreiber "1" -- "N" Zutat : "aktualisiert"
Barbetreiber "1" -- "N" Marketing : "erstellt Kampagnen"
@enduml